# Generated by Django 2.2.5 on 2019-11-16 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_treasure_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treasure',
            old_name='like',
            new_name='likes',
        ),
    ]
